prompt1 = input("Enter a floating point number: ")
prompt2 = input("Enter an integer: ")
prompt1 = float(prompt1)
prompt2 = int(prompt2)
result = round(prompt1 ** prompt2,3)
print(prompt1,"to the power of",prompt2,"is",result)
